export const entries = [
  {
    rm: ["bb", "av", "rb", "pb", "rm", "ab"],
    av: ["bb", "rb", "rm", "av", "pb", "ab"],
    ab: ["pb", "rb", "bb", "av", "rm", "ab"],
    rb: ["bb", "rb", "av", "rm", "pb", "ab"],
    bb: ["bb", "rb", "av", "rm", "pb", "ab"],
  },
  {
    rm: ["rm", "bb", "ab", "in", "pb", "rb", "av"],
    rb: ["rm", "bb", "in", "av", "rb", "ab", "pb"],
    pb: ["rm", "pb", "av", "iv", "rb", "ab", "bb"],
    in: ["av", "pb", "in", "bb", "rb", "ab", "rm"],
    bb: ["rb", "ab", "pb", "rm", "av", "bb", "in"],
    ab: ["rm", "bb", "in", "ab", "av", "rb", "pb"],
  },
  {
    rm: ["av", "rm", "ab", "pb", "rb", "in", "bb"],
    av: ["av", "ab", "bb", "rm", "rb", "in", "pb"],
    pb: ["av", "rm", "bb", "pb", "rb", "in", "ab"],
    in: ["av", "rb", "bb", "pb", "ab", "in", "rm"],
    bb: ["av", "rb", "bb", "ab", "rm", "in", "pb"],
    ab: ["av", "pb", "bb", "rm", "rb", "in", "ab"],
  },
  {
    pb: ["bb", "pb", "rm", "ab", "rb", "in", "av"],
    in: ["av", "ab", "pb", "rm", "bb", "rb", "in"],
    ab: ["bb", "rm", "pb", "rb", "ab", "in", "av"],
    rb: ["ab", "pb", "rb", "bb", "rm", "av", "in"],
    bb: ["bb", "ab", "pb", "rb", "rm", "in", "av"],
    av: ["bb", "rm", "pb", "rb", "ab", "av", "in"],
  },
  {
    rm: ["ab", "av", "in", "pb", "bb", "rm", "rb"],
    in: ["bb", "av", "in", "rm", "ab", "pb", "rb"],
    av: ["rb", "av", "ab", "pb", "in", "rm", "bb"],
    pb: ["bb", "av", "rb", "pb", "in", "rm", "ab"],
    rb: ["pb", "av", "bb", "in", "rb", "rm", "ab"],
    ab: ["ab", "av", "rm", "bb", "in", "rb", "pb"],
  },
  {
    in: ["bb", "av", "ab", "rb", "pb", "rm", "in"],
    bb: ["bb", "ab", "rm", "av", "rb", "pb", "in"],
    av: ["bb", "pb", "rm", "av", "ab", "in", "rb"],
    rm: ["pb", "ab", "rm", "av", "rb", "in", "bb"],
    rb: ["pb", "rb", "rm", "av", "ab", "in", "bb"],
    pb: ["av", "rb", "rm", "in", "pb", "ab", "bb"],
  },
  {
    ab: ["rm", "bb", "ab", "av", "pb", "rb", "in"],
    bb: ["ab", "pb", "in", "bb", "rm", "rb", "av"],
    av: ["av", "bb", "rb", "in", "ab", "rm", "pb"],
    rm: ["bb", "ab", "rb", "in", "rm", "pb", "av"],
    rb: ["rm", "bb", "pb", "in", "ab", "rb", "av"],
    pb: ["ab", "bb", "rb", "av", "in", "rm", "pb"],
  },
  {
    pb: ["bb", "rb", "ab", "pb", "rm", "in", "av"],
    rb: ["bb", "rb", "ab", "pb", "rm", "in", "av"],
    bb: ["bb", "rb", "ab", "pb", "rm", "in", "av"],
    av: ["bb", "pb", "ab", "rb", "rm", "in", "av"],
    in: ["rb", "rm", "bb", "ab", "in", "pb", "av"],
    rm: ["bb", "rb", "rm", "pb", "av", "ab", "in"],
  },
  // missing 2 rounds
  {
    bb: ["ab", "rb", "in", "rm", "bb", "mi", "av"],
    in: ["rm", "in", "ab", "rb", "av", "bb", "mi"],
    ab: ["ab", "mi", "in", "rm", "bb", "rb", "av"],
    rb: ["ab", "mi", "in", "rb", "bb", "rm", "av"],
    mi: ["ab", "in", "mi", "bb", "av", "rm", "rb"],
    rm: ["bb", "mi", "in", "ab", "rb", "rm", "av"],
  },
  {
    bb: ["rm", "rb", "in", "pb", "ab", "bb", "av"],
    in: ["rm", "bb", "in", "ab", "pb", "rb", "av"],
    ab: ["ab", "rb", "av", "pb", "rm", "bb", "in"],
    rb: ["pb", "rb", "av", "ab", "rm", "bb", "in"],
    av: ["rm", "rb", "ab", "in", "pb", "bb", "av"],
    rm: ["pb", "rb", "av", "in", "rm", "bb", "ab"],
  },
];
